@echo off

TITLE Compiling All Files, Dude.

javac "net\sourceforge\jetris\Figure.java"
TITLE Compiling All Files, Dude..
javac "net\sourceforge\jetris\Figures.java"
TITLE Compiling All Files, Dude...
javac "net\sourceforge\jetris\HTMLLink.java"
TITLE Compiling All Files, Dude....
javac "net\sourceforge\jetris\SplashScreen.java"
TITLE Compiling All Files, Dude.....
javac "net\sourceforge\jetris\FigureFactory.java"
TITLE Compiling All Files, Dude......
javac "net\sourceforge\jetris\HelpDialog.java"
TITLE Compiling All Files, Dude.......
javac "net\sourceforge\jetris\TetrisGrid.java"
TITLE Compiling All Files, Dude........
javac "net\sourceforge\jetris\JetrisMainFrame.java"
TITLE Compiling All Files, Dude.........
javac "res\ResClass.java"
TITLE Compiling All Files, Dude..........
javac "JetrisMain.java"
TITLE Compiling All Files, Dude...........
javac "net\sourceforge\jetris\io\HiScore.java"
TITLE Compiling All Files, Dude............
javac "net\sourceforge\jetris\io\PublishHiScore.java"
TITLE Done Compiling!!!

